## Data Cleaning -

2020 CitiBike Data

In [1]:
#importing things
import pandas as pd
import os
import numpy as np

### January

In [3]:
#importing CSVs

#pulling the CSV file to reach the dataframe
f_path = os.path.join('../resources', 'January.csv')

# #print dataframe 
january_df = pd.read_csv(f_path)

january_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.3910,2020-01-31 23:38:33.6910,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,1
26016,122,2020-01-31 23:30:59.3670,2020-01-31 23:33:01.6870,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,1
26017,201,2020-01-31 23:42:34.8460,2020-01-31 23:45:55.8780,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,1
26018,300,2020-01-31 23:45:00.6800,2020-01-31 23:50:00.8740,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,2
26019,721,2020-01-31 23:48:35.1700,2020-02-01 00:00:36.4060,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,1

## February

In [4]:
f_path = os.path.join('../resources', 'February.csv')

# #print dataframe 
feb_df = pd.read_csv(f_path)

feb_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22957,262,2020-02-29 23:40:53.1620,2020-02-29 23:45:15.3180,3639,Harborside,40.719252,-74.034234,3214,Essex Light Rail,40.712774,-74.036486,42467,Subscriber,1967,1
22958,216,2020-02-29 23:41:01.3350,2020-02-29 23:44:38.0350,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42377,Subscriber,1958,1
22959,101,2020-02-29 23:45:22.1700,2020-02-29 23:47:03.2970,3214,Essex Light Rail,40.712774,-74.036486,3681,Grand St,40.715178,-74.037683,42485,Subscriber,1967,1
22960,279,2020-02-29 23:47:56.8380,2020-02-29 23:52:36.6400,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42531,Subscriber,1988,1
22961,212,2020-02-29 23:49:18.4510,2020-02-29 23:52:50.7490,3184,Paulus Hook,40.714145,-74.033552,3276,Marin Light Rail,40.714584,-74.042817,42385,Subscriber,1967,1

## Concat Jan/Feb

In [12]:
combined = january_df.append(feb_df)

In [13]:
combined

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22957,262,2020-02-29 23:40:53.1620,2020-02-29 23:45:15.3180,3639,Harborside,40.719252,-74.034234,3214,Essex Light Rail,40.712774,-74.036486,42467,Subscriber,1967,1
22958,216,2020-02-29 23:41:01.3350,2020-02-29 23:44:38.0350,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42377,Subscriber,1958,1
22959,101,2020-02-29 23:45:22.1700,2020-02-29 23:47:03.2970,3214,Essex Light Rail,40.712774,-74.036486,3681,Grand St,40.715178,-74.037683,42485,Subscriber,1967,1
22960,279,2020-02-29 23:47:56.8380,2020-02-29 23:52:36.6400,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42531,Subscriber,1988,1
22961,212,2020-02-29 23:49:18.4510,2020-02-29 23:52:50.7490,3184,Paulus Hook,40.714145,-74.033552,3276,Marin Light Rail,40.714584,-74.042817,42385,Subscriber,1967,1

In [14]:
## read in March

f_path = os.path.join('../resources', 'March.csv')

# #print dataframe 
mar_df = pd.read_csv(f_path)

mar_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1
17715,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1
17716,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1
17717,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1
17718,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1

In [16]:
## concat to combined

mar_com = combined.append(mar_df)

In [17]:
mar_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1
17715,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1
17716,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1
17717,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1
17718,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1

In [18]:
## april 
f_path = os.path.join('../resources', 'April.csv')

# #print dataframe 
apr_df = pd.read_csv(f_path)

apr_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1

In [19]:
apr_com = mar_com.append(apr_df)

In [21]:
apr_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1

In [22]:
#may
f_path = os.path.join('../resources', 'May.csv')

# #print dataframe 
may_df = pd.read_csv(f_path)

may_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,349,2020-05-01 00:09:45.5860,2020-05-01 00:15:35.2930,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42581,Customer,1969,0
1,138,2020-05-01 01:11:22.5280,2020-05-01 01:13:41.2460,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42105,Subscriber,1949,1
2,229,2020-05-01 05:31:29.5350,2020-05-01 05:35:19.2400,3483,Montgomery St,40.719420,-74.050990,3186,Grove St PATH,40.719586,-74.043117,42320,Customer,1984,1
3,261,2020-05-01 05:51:39.3960,2020-05-01 05:56:00.9370,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,42170,Subscriber,1974,2
4,168,2020-05-01 06:06:31.9510,2020-05-01 06:09:20.1410,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,42352,Subscriber,1966,1

In [23]:
#combine
may_com = apr_com.append(may_df)

In [25]:
may_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25072,395,2020-05-31 23:35:50.9460,2020-05-31 23:42:26.5300,3202,Newport PATH,40.727224,-74.033759,3276,Marin Light Rail,40.714584,-74.042817,42250,Subscriber,1992,1
25073,1681,2020-05-31 23:38:30.8240,2020-06-01 00:06:32.0360,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42396,Customer,1997,1
25074,1657,2020-05-31 23:39:07.2680,2020-06-01 00:06:44.5740,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42331,Customer,1987,1
25075,420,2020-05-31 23:45:28.3290,2020-05-31 23:52:28.3680,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,40517,Subscriber,1999,1
25076,87,2020-05-31 23:50:55.8390,2020-05-31 23:52:23.0920,3272,Jersey & 3rd,40.723332,-74.045953,3211,Newark Ave,40.721525,-74.046305,42314,Subscriber,1976,1

In [26]:
#june
f_path = os.path.join('../resources', 'June.csv')

# #print dataframe 
june_df = pd.read_csv(f_path)

june_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,Subscriber,1987,1
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,Subscriber,1988,1
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,Subscriber,1987,1
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,Subscriber,1987,1
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,Subscriber,1972,2

In [27]:
#combine june

jun_com = may_com.append(june_df)

In [28]:
jun_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36916,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0
36917,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0
36918,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0
36919,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0
36920,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2

In [29]:
#july 
f_path = os.path.join('../resources', 'July.csv')

# #print dataframe 
jul_df = pd.read_csv(f_path)

jul_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2333,2020-07-01 00:23:19.8220,2020-07-01 01:02:13.2980,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,42579,Customer,1969,0
1,1203,2020-07-01 00:27:45.2420,2020-07-01 00:47:49.1960,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3202,Newport PATH,40.727224,-74.033759,42564,Subscriber,1965,1
2,786,2020-07-01 00:34:17.8680,2020-07-01 00:47:24.6310,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3225,Baldwin at Montgomery,40.723659,-74.064194,42219,Subscriber,1994,1
3,1488,2020-07-01 00:51:07.5310,2020-07-01 01:15:56.0200,3677,Glenwood Ave,40.727551,-74.071061,3194,McGinley Square,40.725340,-74.067622,44424,Subscriber,1995,2
4,2682,2020-07-01 00:51:16.3880,2020-07-01 01:35:58.4590,3191,Union St,40.718211,-74.083639,3193,Lincoln Park,40.724605,-74.078406,42186,Subscriber,1993,1

In [30]:
#combine them
jul_com = jun_com.append(jul_df)

In [31]:
jul_com.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2

In [32]:
#august 
f_path = os.path.join('../resources', 'August.csv')

# #print dataframe 
aug_df = pd.read_csv(f_path)

aug_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,Subscriber,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42310,Customer,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42346,Customer,1995,2

In [33]:
#combine
aug_com = jul_com.append(aug_df)

In [34]:
aug_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [35]:
#september
f_path = os.path.join('../resources', 'September.csv')

# #print dataframe 
sept_df = pd.read_csv(f_path)

sept_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,45656,Subscriber,1992,1
1,193,2020-09-01 00:49:00.7370,2020-09-01 00:52:14.3640,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,45352,Subscriber,1991,1
2,273,2020-09-01 00:51:44.5870,2020-09-01 00:56:17.7160,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,44424,Subscriber,1969,1
3,1419,2020-09-01 00:52:48.3160,2020-09-01 01:16:28.0490,3203,Hamilton Park,40.727596,-74.044247,3270,Jersey & 6th St,40.725289,-74.045572,42240,Subscriber,1986,1
4,254,2020-09-01 00:56:16.7170,2020-09-01 01:00:31.0870,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,42434,Subscriber,1992,1

In [37]:
#combine
sept_com = aug_com.append(sept_df)

In [38]:
sept_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53828,270,2020-10-13 15:05:35.0860,2020-10-13 15:10:05.3430,3207,Oakland Ave,40.737604,-74.052478,3640,Journal Square,40.733670,-74.062500,44744,Subscriber,1963,2
53829,400,2020-10-13 15:09:03.4890,2020-10-13 15:15:43.9750,3209,Brunswick St,40.724176,-74.050656,3209,Brunswick St,40.724176,-74.050656,45345,Subscriber,1984,1
53830,206,2020-10-13 15:11:34.3500,2020-10-13 15:15:00.5030,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,47019,Subscriber,1993,1
53831,216,2020-10-13 15:11:49.1510,2020-10-13 15:15:25.6930,3195,Sip Ave,40.730897,-74.063913,3225,Baldwin at Montgomery,40.723659,-74.064194,42191,Subscriber,1966,1
53832,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,-74.043117,47255,Subscriber,1991,1

In [39]:
#october
f_path = os.path.join('../resources', 'October.csv')

# #print dataframe 
oct_df = pd.read_csv(f_path)

oct_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1

In [41]:
#commbine
oct_com = sept_com.append(oct_df)

In [42]:
oct_com

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30081,1054,2020-10-31 23:32:22.8650,2020-10-31 23:49:57.5320,3198,Heights Elevator,40.748716,-74.040443,3678,Fairmount Ave,40.725726,-74.071959,17231,Customer,1969,0
30082,156,2020-10-31 23:33:22.7310,2020-10-31 23:35:59.4930,3185,City Hall,40.717733,-74.043845,3681,Grand St,40.715178,-74.037683,46532,Subscriber,1981,1
30083,1858,2020-10-31 23:37:01.7010,2020-11-01 00:07:59.7530,3278,Monmouth and 6th,40.725685,-74.048790,3278,Monmouth and 6th,40.725685,-74.048790,42230,Subscriber,1998,1
30084,1809,2020-10-31 23:37:46.1430,2020-11-01 00:07:55.2740,3278,Monmouth and 6th,40.725685,-74.048790,3278,Monmouth and 6th,40.725685,-74.048790,45341,Subscriber,1999,1
30085,395,2020-10-31 23:40:06.3530,2020-10-31 23:46:42.0640,3481,York St,40.716490,-74.041050,3273,Manila & 1st,40.721651,-74.042884,45647,Subscriber,1967,1

In [43]:
#november
f_path = os.path.join('../resources', 'November.csv')

# #print dataframe 
nov_df = pd.read_csv(f_path)

nov_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,756,2020-11-01 00:11:32.6250,2020-11-01 00:24:09.5850,3275,Columbus Drive,40.718355,-74.038914,3225,Baldwin at Montgomery,40.723659,-74.064194,42436,Subscriber,1984,1
1,584,2020-11-01 00:14:20.4820,2020-11-01 00:24:04.7820,3681,Grand St,40.715178,-74.037683,3209,Brunswick St,40.724176,-74.050656,46532,Customer,1969,0
2,403,2020-11-01 00:22:55.8820,2020-11-01 00:29:39.0950,3203,Hamilton Park,40.727596,-74.044247,3483,Montgomery St,40.719420,-74.050990,35139,Subscriber,1980,1
3,498,2020-11-01 00:41:37.4270,2020-11-01 00:49:55.7010,3268,Lafayette Park,40.713464,-74.062859,3213,Van Vorst Park,40.718489,-74.047727,46539,Customer,1969,0
4,151,2020-11-01 00:53:21.2340,2020-11-01 00:55:52.8060,3185,City Hall,40.717733,-74.043845,3276,Marin Light Rail,40.714584,-74.042817,44388,Subscriber,1986,1

In [44]:
#combine
nov_com = oct_com.append(nov_df)

In [45]:
nov_com.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2

In [46]:
#december (finally)
f_path = os.path.join('../resources', 'December.csv')

# #print dataframe 
dec_df = pd.read_csv(f_path)

dec_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,146,2020-12-01 00:02:50.1450,2020-12-01 00:05:16.1940,3202,Newport PATH,40.727224,-74.033759,3199,Newport Pkwy,40.728745,-74.032108,42308,Subscriber,1989,2
1,572,2020-12-01 00:11:57.3910,2020-12-01 00:21:30.2510,3640,Journal Square,40.733670,-74.062500,3280,Astor Place,40.719282,-74.071262,18568,Subscriber,1997,2
2,387,2020-12-01 00:14:49.3610,2020-12-01 00:21:16.8730,3640,Journal Square,40.733670,-74.062500,3194,McGinley Square,40.725340,-74.067622,44543,Subscriber,1960,1
3,188,2020-12-01 00:45:06.3680,2020-12-01 00:48:14.4280,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,43098,Subscriber,1998,1
4,594,2020-12-01 01:17:17.0110,2020-12-01 01:27:11.9400,3212,Christ Hospital,40.734786,-74.050444,3209,Brunswick St,40.724176,-74.050656,44723,Subscriber,1988,1

In [47]:
#combined
total_yr = nov_com.append(dec_df)

In [48]:
total_yr

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [49]:
total_yr.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [50]:
total_yr['gender']= total_yr['gender'].astype(str)

In [51]:
total_yr.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                      object
dtype: object

In [52]:
#change numerical values to male, female, not specified
not_spec = total_yr.replace(to_replace ="0", 
                 value ="not specified") 

male = not_spec.replace(to_replace ="1", 
               value ="male")

gender = male.replace(to_replace ="2", 
                  value ="female") 

# total_yr.replace(to_replace ="1", 
#                  value ="male") 

# total_yr.replace(to_replace ="2", 
#                  value ="female") 

gender

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,female
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,female
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,male
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,not specified
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,not specified
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,not specified
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,male
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,not specified
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,male

In [53]:
# change usertype

subscriber= gender.replace(to_replace ="Subscriber", 
                value ="Annual Member")

user_type = subscriber.replace(to_replace ="Customer", 
                  value ="24 Hr / 3 Day Pass") 

user_type

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Annual Member,1984,female
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Annual Member,1989,female
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,24 Hr / 3 Day Pass,1989,male
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,24 Hr / 3 Day Pass,1969,not specified
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Annual Member,1983,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,24 Hr / 3 Day Pass,1969,not specified
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,24 Hr / 3 Day Pass,1969,not specified
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,24 Hr / 3 Day Pass,1998,male
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,24 Hr / 3 Day Pass,1969,not specified
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Annual Member,1982,male

In [54]:
#export as CSV
total_yr.to_csv('2020.csv', index=False)

In [99]:
import os
file_list=os.listdir()
combined=pd.DataFrame()
for each_file in file_list: 
    if each_file[-4]=='.csv': 
        # concact to combined
        pd.concat([combined, pd.read_csv(each_file)], axis=1)

Empty DataFrame
Columns: []
Index: []